# Generated by Django 4.1.5 on 2023-01-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_code", models.CharField(max_length=24, verbose_name="id_code")),
                (
                    "created_at",
                    models.CharField(max_length=100, verbose_name="Дата создания"),
                ),
                ("person_id", models.IntegerField(verbose_name="id человека")),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("secondName", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("lastName", models.CharField(max_length=30, verbose_name="Отчество")),
                (
                    "fullName",
                    models.CharField(max_length=100, verbose_name="Полное имя"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Почта"),
                ),
                ("phone", models.IntegerField(verbose_name="Номер телефона")),
                (
                    "position",
                    models.CharField(max_length=150, verbose_name="Должность"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
            ],
        ),
    ]
